# Generated by Django 3.0.5 on 2021-09-26 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210926_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
