# Generated by Django 3.0.5 on 2021-09-27 00:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210926_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='student', max_length=255),
        ),
        migrations.CreateModel(
            name='AssignmentDelivery',
            fields=[
                ('identifier', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(default='', max_length=80)),
                ('file_attach', models.FileField(upload_to='uploads/')),
                ('delivery_date', models.DateTimeField(default=datetime.datetime(2021, 9, 27, 0, 58, 56, 601914))),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Product')),
                ('product_step', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ProductStep')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Project')),
            ],
        ),
    ]
