# Generated by Django 3.0.5 on 2021-09-27 01:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210927_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentdelivery',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
        migrations.AlterField(
            model_name='assignmentdelivery',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 27, 1, 7, 35, 46290)),
        ),
    ]
