# Generated by Django 3.0.5 on 2021-10-19 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210927_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentdelivery',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 19, 18, 40, 25, 539527)),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='productstep',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='productstep',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='productstep',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
