# Generated by Django 3.0.5 on 2021-11-02 00:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20211024_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentdelivery',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Group'),
        ),
        migrations.AlterField(
            model_name='assignmentdelivery',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 2, 0, 28, 10, 512781)),
        ),
    ]
