# Generated by Django 3.0.5 on 2021-11-03 02:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20211102_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentdelivery',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 3, 2, 20, 4, 45840)),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('identifier', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.CharField(default='', max_length=1500)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Group')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Product')),
                ('product_step', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ProductStep')),
            ],
        ),
    ]
